### ISSUE TITLE
Bento

### ISSUE THREAD

**Issue by pjerryhu** [greko6/xfb2xfb#28]
I wonder what bento jupyter notebook like service is in Open source world

**Comment by greko6** [comment]
Out of curiosity... What bento had that jupyter doesn't?

**Comment by pjerryhu** [comment]
I was thinking about packages like `pvc` such that bento will be able to directly connect with HDFS and Presto engine and do big data analysis immediately.

**Comment by pjerryhu** [comment]
Found it https://zeppelin.apache.org/
